#!/bin/sh

. cfg.sh

docker exec ${DB_CONTAINER} /bin/bash -c "
  export NLS_LANG=american_america.AL32UTF8
  export ORACLE_SID=XE
  . oraenv

  sqlplus sys/123@//localhost:1521/XEPDB1 as sysdba <<- EOF

    GRANT SELECT, FLASHBACK ON SYS.CCOL$ TO c##dbzuser;
    GRANT SELECT, FLASHBACK ON SYS.CDEF$ TO c##dbzuser;
    GRANT SELECT, FLASHBACK ON SYS.COL$ TO c##dbzuser;
    GRANT SELECT, FLASHBACK ON SYS.DEFERRED_STG$ TO c##dbzuser;
    GRANT SELECT, FLASHBACK ON SYS.ECOL$ TO c##dbzuser;
    GRANT SELECT, FLASHBACK ON SYS.LOB$ TO c##dbzuser;
    GRANT SELECT, FLASHBACK ON SYS.LOBCOMPPART$ TO c##dbzuser;
    GRANT SELECT, FLASHBACK ON SYS.LOBFRAG$ TO c##dbzuser;
    GRANT SELECT, FLASHBACK ON SYS.OBJ$ TO c##dbzuser;
    GRANT SELECT, FLASHBACK ON SYS.TAB$ TO c##dbzuser;
    GRANT SELECT, FLASHBACK ON SYS.TABCOMPART$ TO c##dbzuser;
    GRANT SELECT, FLASHBACK ON SYS.TABPART$ TO c##dbzuser;
    GRANT SELECT, FLASHBACK ON SYS.TABSUBPART$ TO c##dbzuser;
    GRANT SELECT, FLASHBACK ON SYS.TS$ TO c##dbzuser;
    GRANT SELECT, FLASHBACK ON SYS.USER$ TO c##dbzuser;
    GRANT SELECT, FLASHBACK ON XDB.XDB\$TTSET TO c##dbzuser;

    DECLARE
    CURSOR C1 IS SELECT TOKSUF FROM XDB.XDB\$TTSET;
    CMD VARCHAR2(2000);
    BEGIN
    FOR C IN C1 LOOP
          CMD := 'GRANT SELECT, FLASHBACK ON XDB.X\$NM' || C.TOKSUF || ' TO c##dbzuser';
    EXECUTE IMMEDIATE CMD;
    CMD := 'GRANT SELECT, FLASHBACK ON XDB.X\$QN' || C.TOKSUF || ' TO c##dbzuser';
    EXECUTE IMMEDIATE CMD;
    CMD := 'GRANT SELECT, FLASHBACK ON XDB.X\$PT' || C.TOKSUF || ' TO c##dbzuser';
    EXECUTE IMMEDIATE CMD;
    END LOOP;
    END;
    /

    EXIT;
  EOF
"

echo "- all OK"