#!/bin/sh

. cfg.sh

docker exec ${DB_CONTAINER} /bin/bash -c "
  export NLS_LANG=american_america.AL32UTF8
  export ORACLE_SID=XE
  . oraenv

  sqlplus sys/123@//localhost:1521/XEPDB1 as sysdba <<- EOF

    ALTER SESSION SET CONTAINER = XEPDB1;
    CREATE TABLESPACE TBLS1
      DATAFILE '/opt/oracle/oradata/XE/XEPDB1/tbls1_01.dbf'
      SIZE 100M AUTOEXTEND ON NEXT 100M;

    ALTER TABLESPACE TBLS1 FORCE LOGGING;

    CREATE USER USR1 IDENTIFIED BY USR1PWD
        DEFAULT TABLESPACE TBLS1
        TEMPORARY TABLESPACE TEMP
        QUOTA UNLIMITED ON TBLS1;

    GRANT CREATE SESSION TO USR1;
    GRANT CREATE TABLE TO USR1;
    GRANT CREATE SEQUENCE TO USR1;
    GRANT CREATE TRIGGER TO USR1;
    GRANT CREATE PROCEDURE TO USR1;
    GRANT CREATE VIEW TO USR1;

    CREATE TABLE USR1.ADAM1(
        ID         NUMBER NOT NULL,
        NAME       VARCHAR2(30),
        COUNT      NUMBER,
        START_TIME TIMESTAMP
    );
    ALTER TABLE USR1.ADAM1 ADD CONSTRAINT ADAM1PK PRIMARY KEY(ID);

    ALTER TABLE USR1.ADAM1 ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS;

    EXIT;
  EOF
"

echo "- all OK"