ALTER SESSION SET CONTAINER = CDB$ROOT;
ALTER SYSTEM ARCHIVE LOG CURRENT;

CREATE TABLESPACE TBLS1 DATAFILE SIZE 100M AUTOEXTEND ON NEXT 100M;
ALTER TABLESPACE TBLS1 FORCE LOGGING;

ALTER SESSION SET CONTAINER = XEPDB1;
CREATE TABLESPACE TBLS1 DATAFILE SIZE 100M AUTOEXTEND ON NEXT 100M;
ALTER TABLESPACE TBLS1 FORCE LOGGING;

ALTER SESSION SET CONTAINER = CDB$ROOT;
CREATE USER C##USR1 IDENTIFIED BY USR1PWD DEFAULT TABLESPACE TBLS1 TEMPORARY TABLESPACE TEMP CONTAINER = ALL;
ALTER USER C##USR1 QUOTA UNLIMITED ON TBLS1;

GRANT CREATE SESSION TO C##USR1 CONTAINER=ALL;
GRANT SET CONTAINER TO C##USR1 CONTAINER=ALL;
GRANT SELECT ON V_$DATABASE TO C##USR1 CONTAINER=ALL;
GRANT SELECT ANY DICTIONARY TO C##USR1 CONTAINER=ALL;
GRANT LOCK ANY TABLE TO C##USR1 CONTAINER=ALL;
GRANT SELECT ANY TABLE TO C##USR1 CONTAINER=ALL;
GRANT FLASHBACK ANY TABLE TO C##USR1 CONTAINER=ALL;
GRANT SELECT_CATALOG_ROLE TO C##USR1 CONTAINER=ALL;


ALTER SESSION SET CONTAINER = XEPDB1;


GRANT CONNECT TO C##USR1;
GRANT RESOURCE TO C##USR1;
GRANT SELECT, FLASHBACK ON SYS.CCOL$ TO C##USR1;
GRANT SELECT, FLASHBACK ON SYS.CDEF$ TO C##USR1;
GRANT SELECT, FLASHBACK ON SYS.COL$ TO C##USR1;
GRANT SELECT, FLASHBACK ON SYS.DEFERRED_STG$ TO C##USR1;
GRANT SELECT, FLASHBACK ON SYS.ECOL$ TO C##USR1;
GRANT SELECT, FLASHBACK ON SYS.LOB$ TO C##USR1;
GRANT SELECT, FLASHBACK ON SYS.LOBCOMPPART$ TO C##USR1;
GRANT SELECT, FLASHBACK ON SYS.LOBFRAG$ TO C##USR1;
GRANT SELECT, FLASHBACK ON SYS.OBJ$ TO C##USR1;
GRANT SELECT, FLASHBACK ON SYS.TAB$ TO C##USR1;
GRANT SELECT, FLASHBACK ON SYS.TABCOMPART$ TO C##USR1;
GRANT SELECT, FLASHBACK ON SYS.TABPART$ TO C##USR1;
GRANT SELECT, FLASHBACK ON SYS.TABSUBPART$ TO C##USR1;
GRANT SELECT, FLASHBACK ON SYS.TS$ TO C##USR1;
GRANT SELECT, FLASHBACK ON SYS.USER$ TO C##USR1;
GRANT SELECT ON SYS.V_$ARCHIVED_LOG TO C##USR1;
GRANT SELECT ON SYS.V_$DATABASE TO C##USR1;
GRANT SELECT ON SYS.V_$DATABASE_INCARNATION TO C##USR1;
GRANT SELECT ON SYS.V_$LOG TO C##USR1;
GRANT SELECT ON SYS.V_$LOGFILE TO C##USR1;
GRANT SELECT ON SYS.V_$PARAMETER TO C##USR1;
GRANT SELECT ON SYS.V_$STANDBY_LOG TO C##USR1;
GRANT SELECT ON SYS.V_$TRANSPORTABLE_PLATFORM TO C##USR1;
GRANT SELECT, FLASHBACK ON XDB.XDB$TTSET TO C##USR1;

DECLARE
CURSOR C1 IS SELECT TOKSUF FROM XDB.XDB$TTSET;
CMD VARCHAR2(2000);
BEGIN
FOR C IN C1 LOOP
        CMD := 'GRANT SELECT, FLASHBACK ON XDB.X$NM' || C.TOKSUF || ' TO C##USR1';
EXECUTE IMMEDIATE CMD;
CMD := 'GRANT SELECT, FLASHBACK ON XDB.X$QN' || C.TOKSUF || ' TO C##USR1';
EXECUTE IMMEDIATE CMD;
CMD := 'GRANT SELECT, FLASHBACK ON XDB.X$PT' || C.TOKSUF || ' TO C##USR1';
EXECUTE IMMEDIATE CMD;
END LOOP;
END;
/

ALTER SESSION SET CONTAINER = CDB$ROOT;
ALTER SYSTEM ARCHIVE LOG CURRENT;