CREATE TABLE C##USR1.ADAM1(
  ID         NUMBER NOT NULL,
  NAME       VARCHAR2(30),
  COUNT      NUMBER,
  START_TIME TIMESTAMP
);
ALTER TABLE C##USR1.ADAM1 ADD CONSTRAINT ADAM1PK PRIMARY KEY(ID);
ALTER TABLE C##USR1.ADAM1 ADD SUPPLEMENTAL LOG DATA (PRIMARY KEY) COLUMNS;
INSERT INTO C##USR1.ADAM1 VALUES (1, 'Adam Leszczyński', 10, TO_DATE('2019-08-01 12:34:56', 'YYYY-MM-DD HH24:MI:SS'));
COMMIT;
UPDATE C##USR1.ADAM1 SET COUNT = COUNT + 1;
COMMIT;
DELETE FROM C##USR1.ADAM1;
COMMIT;
-- DROP TABLE C##USR1.ADAM1;