ALTER SESSION SET CONTAINER = XEPDB1;

DROP TABLESPACE TBLS1 INCLUDING CONTENTS AND DATAFILES;

CREATE TABLESPACE TBLS1 DATAFILE SIZE 100M AUTOEXTEND ON NEXT 100M;
ALTER TABLESPACE TBLS1 FORCE LOGGING;

DROP USER USR1 CASCADE;
CREATE USER USR1 IDENTIFIED BY USR1PWD DEFAULT TABLESPACE TBLS1 TEMPORARY TABLESPACE TEMP;
ALTER USER USR1 QUOTA UNLIMITED ON TBLS1;

GRANT CREATE SESSION TO USR1;
GRANT CREATE TABLE, CREATE SEQUENCE TO USR1;


CREATE TABLE USR1.ADAM1(
ID         NUMBER NOT NULL,
NAME       VARCHAR2(30),
COUNT      NUMBER,
START_TIME TIMESTAMP
);

ALTER TABLE USR1.ADAM1 ADD CONSTRAINT ADAM1PK PRIMARY KEY(ID);
ALTER TABLE USR1.ADAM1 ADD SUPPLEMENTAL LOG DATA (PRIMARY KEY) COLUMNS;
ALTER TABLE USR1.ADAM1 ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS;

INSERT INTO USR1.ADAM1 VALUES (1, 'Adam Leszczyński', 10, TO_DATE('2019-08-01 12:34:56', 'YYYY-MM-DD HH24:MI:SS'));
COMMIT;

UPDATE USR1.ADAM1 SET COUNT = COUNT + 1;
COMMIT;

DELETE FROM USR1.ADAM1;
COMMIT;

-- DROP TABLE USR1.ADAM1;